name: Todo Setup

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Setup maven wrapper
      shell: bash
      run: chmod +x mvnw

    - name: Pull todo-app image
      shell: bash
      run: docker pull nataliamaslova/todo-app:latest

    - name: Run todo-app container
      shell: bash
      run: docker run -d -p 8080:4242 --name todo-app nataliamaslova/todo-app:latest # -e VERBOSE=1 todo-app

    - name: Wait for app start
      shell: bash
      run: sleep 5